name: insuguia_mobile
description: "Desenvolvimento de ferramenta digital automatizada para orientação de aplicação da diretriz para tratamento da Hiperglicemia Hospitalar."

environment:
  sdk: ^3.8.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  postgres: ^3.0.1
  intl: any
  cupertino_icons: ^1.0.8  

publish_to: 'none' 

version: 1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  